version: '3.4'

services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:4.1.0
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
  build:
    command: jekyll build
    image: jekyll/jekyll:4.1.0
    volumes:
      - .:/srv/jekyll